<?php

/**
 * Implements hook_menu().
 */
function postit_menu()
{
    $items['admin/structure/postit/manage'] = array(
        'title' => 'PostIt Admin',
        'description' => 'Manage PostIT structure',
        'page callback' => 'postit_info',
        'access arguments' => array('administer postits'),
    );

    $items['admin/structure/postit/add'] = array(
        'title' => 'Add PostIT!',
        'page callback' => 'postit_add',
        'access arguments' => array('create postit'),
    );

    $items['admin/structure/postit/%postit'] = array(
        'title callback' => 'postit_page_title',
        'title arguments' => array(3),
        'page callback' => 'postit_page_view',
        'page arguments' => array(3),
        'access arguments' => array('view postits'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_permission().
 */
function postit_permission() {
    return array(
        'administer postits' =>  array(
            'title' => t('Administer postits'),
            'restrict access' => TRUE,
        ),
        'view postits' => array(
            'title' => t('View PostIts'),
        ),
        'create postit' => array(
            'title' => t('Create PostIts'),
        )
    );
}

function postit_info() {
    return ('Welcome to the administration page for your Postits!');
}

function postit_page_title($postit){
    return $postit->pid;
}

function postit_page_view($postit, $view_mode = 'full'){
    $postit->content = array();

    // Build fields content.
    field_attach_prepare_view('postit', array($postit->pid => $postit), $view_mode);
    entity_prepare_view('postit', array($postit->pid => $postit));
    $postit->content += field_attach_view('postit', $postit, $view_mode);

    return $postit->content;
}

function postit_field_extra_fields() {
    $return = array();
    $return['postit']['postit'] = array(
        'form' => array(
            'note' => array(
                'label' => t('Note'),
                'description' => t('PostIt Note'),
            ),
        ),
    );

    return $return;
}

function postit_add_form($form, &$form_state, $postit) {
    $form['note'] = array(
        '#type' => 'textfield',
        '#title' => t('Note'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );

    field_attach_form('postit', $postit, $form, $form_state);

    return $form;
}

function postit_add() {
    $postit = (object) array (
        'pid' => '',
        'type' => 'postit',
        'note' => '',
    );

    return drupal_get_form('postit_add_form', $postit);
}

function postit_add_form_validate($form, &$form_state) {
    $postit_submisttion = (object) $form_state['values'];
    field_attach_form_validate('postit', $postit_submisttion, $form, $form_state);
}

function postit_add_form_submit($form, &$form_state) {
    $postit_submission = (object) $form_state['values'];
    field_attach_submit('postit', $postit_submission, $form, $form_state);
    $postit = postit_save($postit_submission);
    $form_state['redirect'] = "postit/$postit->pid";
}

function postit_save(&$postit) {
    return entity_get_controller('postit')->save($postit);
}